#Arcadia Patch Create runtime settings
#Wed Jul 01 19:51:47 MSK 2026
belt.enabled=true
chute.enabled=true
createDrops.despawnTicks=1200
createDrops.enabled=false
factoryGauge.enabled=true
fluid.enabled=true
master.enabled=true
throttle.mode=OFF
throttle.staticInterval=2
