#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 22 10:11:57 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
